### ISSUE TITLE
[Task Manager] Unit task registeration and deployment

### ISSUE THREAD

**Issue by majunze2001** [cornserve-ai/cornserve#44]
Currently, all the unit tasks are predefined. However, cluster operators should be able to define and deploy new unit tasks for end users. Additionally, the resource manager (#28) should be able to allocate resources for new unit tasks.

**Comment by jaywonchung** [comment]
Design requirements
1. A newly written unit task (task, task input, and task output classes) should be deployed to the cluster *without* having to redeploy the entire Cornserve system.
2. We still want to put the three new unit task classes so that app writers or composite task writers get good quality Python autocomplete and type safety.

Also related to #53, this is making unit task definitions (three classes) and concrete instantiations of unit tasks (e.g., `LLMTask` objects with all fields like `model_id` filled in) as cluster-wide global state that can be dynamically queried from every Cornserve control plane service. Conceptually, it's centralizing the `TASK_REGISTRY` variable into a cluster-wise unique and global state store.

New unit task registration and use in new apps
1. Python source code for the new unit task is written and put inside `cornserve.tasklib`.
2. Cornserve CLI is invoked, which reads in unit task definitions in `cornserve.tasklib`, contrasts it with what is currently deployed in the cluster, and applies the diff.
3. The new unit task source code needs to be made available to other users via a new release of the tasklib. This is one reason to separate out the tasklib completely out of `cornserve` so that we don't have to release a new `cornserve` version every time we add a new unit task.
4. After that, apps that mention new unit tasks can be deployed through the gateway.
5. The gateway, resource manager, and task dispatcher can query the cluster-wide task registry dynamically to retrieve the unit task's source code and dynamically parse and import required classes. This is shared behavior, so it can be abstracted out by a submodule inside `cornserve.services.task_registry`.

Implementation of the cluster-wide task registry
- State and its representation
   - Unit task class source code can be expressed as a single string. Basically the whole Python module as a single long string, including imports and three classes.
   - Concrete instantiations of a unit task can be expressed as a pair of the name of the unit task and a JSON/YAML field list. Thus, this also becomes a single source of truth for which unit task is currently deployed on the data plane.
   - Profiling results of a concrete instantiation of a unit task can be expressed as a pair of the name of the concrete unit task instantiation and a JSON/YAML object.
   - Each of the three things in the above can be its own K8s CRD.
- Storage of state during cluster operation
   - If we make these CRDs, then K8s handles state management during operation.
   - The Cornserve CLI should have logic that goes from unit task Python source code module to CRD.
- Persistence of state
   - Task definitions can be restored from the tasklib, and we want this to be part of our cluster bootstrapping flow.
   - Task instantiations ought to be cleared out when we restart the cluster because the data plane starts empty.
   - We want profiling results to be persisted across cluster restarts. This is tricky. Not decided on how it should be done.

**Comment by yizhuoliang** [comment]
So here I draft the three CRDs with corresponding examples. The example CRs mimic the `LLMUnitTask`.

As an overview, we have
- `UnitTaskDefinition`, meant to replace the process-wide `TASK_REGISTRY`
- `UnitTaskInstance`, meant to replace the in-memory instantiated `UnitTask` objects
- `ExecutionDescriptor`, meant to replace the process-wide `DESCRIPTOR_REGISTRY`. **_This wasn't discussed above, but users do need this to add new task executors for new UnitTasks._**

## 1. `UnitTaskDefinition` CRD
An example of CR:
```
apiVersion: cornserve.io/v1
kind: UnitTaskDefinition
metadata:
  name: cornserve.unittaskdefinition.llm
  namespace: cornserve
spec:
  taskClassName: "LLMUnitTask"
  sourceCode: |
    somebase64string...
```
Here the `taskClassName` is necessary as there can be multiple UnitTask classes in a single source file (e.g. Prefill/Decode unit tasks).

The drafted CRD:
```
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: unittaskdefinitions.cornserve.io
spec:
  group: cornserve.io
  scope: Namespaced
  names:
    plural: unittaskdefinitions
    singular: unittaskdefinition
    kind: UnitTaskDefinition
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                taskClassName:
                  type: string
                sourceCode:
                  type: string
              required: ["taskClassName", "sourceCode"]
```

## 2. `UnitTaskInstance` CRD
Example CR:
```
apiVersion: cornserve.io/v1
kind: UnitTaskInstance
metadata:
  name: qwen2-vl-7b-instruct-default
  namespace: cornserve
spec:
  definitionRef: cornserve.unittaskdefinition.llm
  config:
    model_id: "Qwen/Qwen2-VL-7B-Instruct"
    receive_embeddings: true
```

Drafted CRD:
```
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: unittaskinstances.cornserve.io
spec:
  group: cornserve.io
  scope: Namespaced
  names:
    plural: unittaskinstances
    singular: unittaskinstance
    kind: UnitTaskInstance
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                definitionRef:
                  type: string
                executionDescriptorName:
                  type: string
                config:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
              required: ["definitionRef", "config"]
```
Note that this CDR has the `executionDescriptorName`, which may seem redundant, but that's indeed a field in a `UnitTask` object. However, all current code in cornserve seem to be ignoring this field right now, it's always `None`.

## 3. `ExecutionDescriptor` CRD
Example CR:
```
apiVersion: cornserve.io/v1
kind: ExecutionDescriptor
metadata:
  name: vllm-execution-strategy
  namespace: cornserve
spec:
  targetTaskType: "LLMUnitTask"
  descriptorName: "VLLMDescriptor"
  isDefault: true
  sourceCode: |
    base64string
```
Here I think using a string encoding also works for storing executor source. One thing to note is `targetTaskType: "LLMUnitTask"` specifies what Task this executor is serving. I'm not sure if using a name of the task class CRD like `cornserve.unittaskdefinition.llm` is better than using the class name.
