### ISSUE TITLE
[K8s] State management via CRDs

### ISSUE THREAD

**Issue by jaywonchung** [cornserve-ai/cornserve#53]
Right now, all state -- including app info, task info, task deployment info, and the mapping between task and task manager -- is in-memory, which makes pods stateful and makes fault-tolerance, upgrade, and scale-out brittle.

Eventually, state management should be done with K8s CRDs so that they are decoupled with the in-memory state of pods and the pods themselves are virtually stateless. CRDs will be the single source of truth, and then pods are restarted or upgraded, in-memory state will be re-built from CRDs.

I can roughly think of the following CRDs we would define, but this is far from a complete plan:

### `CornserveApp`

This is created by the Gateway when a new app is registered.

```yaml
apiVersion: cornserve.ai/v1
kind: CornserveApp
metadata:
  name: vlm-demo
spec:
  source_code: "from cornserve.app.base import AppConfig, ..."
  unitTasks:   # A list of CornserveTask names
    - encoder-qwen-qwen2-vl-7b-instruct-image
    - llm-qwen-qwen2-vl-7b-instruct
status:   # Incrementally updated by the Gateway as the app state changes
  state_message: "Deploying unit tasks"
  registeredAt: "2025-05-24T22:05:00Z"
  deployedAt: nil
  erroredAt: nil
  unregisteredAt: nil
```

### `CornserveTaskClass`

This is created by the Gateway when a new unit task class is registered.

```yaml
apiVersion: cornserve.ai/v1
kind: CornserveTaskClass
metadata:
  name: encoder
spec:
  sourceCode: "..."
  executionDescriptorName: vllm
  schema:
    properties:
      model_id:
        type: string
      modality:
        type: string
        default: image
```

### `CornserveTask`

This is created by the Gateway when a unit task is deployed. The corresponding unit task class should have already been registered (thus the corresponding `CornserveTaskClass` CRD should exist).

```yaml
apiVersion: cornserve.ai/v1
kind: CornserveTask
metadata:
  name: llama-3-demo
spec:
  taskClassName: encoder
  config:
    model_id: "Qwen/Qwen2-VL-7B-Instruct"
status:   # Updated by the Resource Manager
  taskManagerURL: "..."
```

With this, the Task Dispatcher doesn't even have to be notified by the Resource Manager because it can just be watching the creation and updates of `CornserveTask` CRDs.

This is a fair amount of engineering, but I do think this is necessary for us to become more production-ready.
